name: Android CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    working-directory: Android

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: gradle

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Linking Node.js binaries
        run: sudo ln `which node` /usr/bin/node && sudo ln `which npm` /usr/bin/npm

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Installing dependencies
        run: ./gradlew app:npmInstall

      - name: Build with Gradle
        run: ./gradlew build
