name: Generate APK Debug

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  workflow_dispatch:

defaults:
  run:
    working-directory: Android

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Linking Node.js binaries
        run: sudo ln `which node` /usr/bin/node && sudo ln `which npm` /usr/bin/npm 

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-includes: |
            caches
            notifications
            jdks
            ${{ github.workspace }}/.gradle/configuration-cache

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Installing dependencies
        run: ./gradlew app:npmInstall

      - name: Build apk debug
        run: ./gradlew app:assembleDefaultDebug

      - name: Build apk debug
        run: ls app/build/outputs/apk/default/debug/

      - name: Upload MMRL-default-arm64-v8a-debug
        uses: actions/upload-artifact@v3
        with:
          name: MMRL-default-arm64-v8a-debug
          path: ${{ github.workspace }}/Android/app/build/outputs/apk/default/debug/*-default-arm64-v8a-debug.apk

      - name: Upload MMRL-default-armeabi-v7a-debug
        uses: actions/upload-artifact@v3
        with:
          name: MMRL-default-armeabi-v7a-debug
          path: ${{ github.workspace }}/Android/app/build/outputs/apk/default/debug/*-default-armeabi-v7a-debug.apk

      - name: Upload MMRL-default-universal-debug
        uses: actions/upload-artifact@v3
        with:
          name: MMRL-default-universal-debug
          path: ${{ github.workspace }}/Android/app/build/outputs/apk/default/debug/*-default-universal-debug.apk

      - name: Upload MMRL-default-x86-debug
        uses: actions/upload-artifact@v3
        with:
          name: MMRL-default-x86-debug
          path: ${{ github.workspace }}/Android/app/build/outputs/apk/default/debug/*-default-x86-debug.apk

      - name: Upload MMRL-default-x86_64-debug
        uses: actions/upload-artifact@v3
        with:
          name: MMRL-default-x86_64-debug
          path: ${{ github.workspace }}/Android/app/build/outputs/apk/default/debug/*-default-x86_64-debug.apk
