name: Build with Webpack

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Development
        run: |
          npm install --force
          npm run web:dev

      - name: Build Production
        run: |
          npm install --force
          npm run web:prod
