name: Build with Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: Website

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16, 18 ]
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build Development
      run: |
        npm install --force
        npm run web:dev

    - name: Build Production
      run: |
        npm install --force
        npm run web:prod
