name: Build with Webpack

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  IS_WP: ${{ startsWith(github.event.head_commit.message, '[webpack]') }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ env.IS_WP == 'true' }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Development
        run: |
          npm install --force
          npm run web:dev

      - name: Build Production
        run: |
          npm install --force
          npm run web:prod
